server:
  port: 9001
  servlet:
    context-path: /codgen
spring:
  profiles:
    active: local

  datasource:
    username: sa
    password: sa
    url: jdbc:h2:file:${user.dir}/h2_data:loong_codegen;MODE=MySQL
    platform: h2
    driver-class-name: org.h2.Driver
