spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:file:/home/codegen/data/h2_data:loong_codegen;MODE=MySQL
    platform: h2
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

loong:
  codegen:
    sdk:
      tempdir: /home/codegen/sdk

logging:
  level:
    com.wuxp: info